version: "3"

services:
  nginxproxy:
    depends_on:
      - nginx
      - mariadb
      - wordpress
      - jupyter
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"

  nginx:
    image: nginx:latest
    container_name: web
    restart: always
    volumes:
      - "./web:/usr/share/nginx/html"

  mariadb:
    image: mariadb:10.3.10
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"

  wordpress:
    depends_on:
       - mariadb
    build: ./
      #context: ./
      #dockerfile: Dockerfile
    container_name: wordpress
    #ports:
    #  - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - "./wordpress:/var/www/html"

  flask:
     build: ./flask_docker
     restart: always
     container_name: flask
     command: gunicorn -w 1 -b 0.0.0.0:80 wsgi:server
  
  jupyter:
    image: jupyter:v1.1 
    container_name: jupyter
    restart: always
    volumes:
      - "./jupyter:/home/workspace"

#volumes:
#  nginx:
#  web:
#  data:
#  wordpress:
#  jupyter: 
